Q1.	Create examples of zero vector, one vector, square matrix, diagonal matrix, identity matrix, and symmetric matrix one by one, and represent vectors and matrices with NumPy.

In [1]:
import numpy as np

In [2]:
zero_vector = np.zeros(5)
zero_vector

array([0., 0., 0., 0., 0.])

In [3]:
one_vector = np.ones(3)
one_vector

array([1., 1., 1.])

In [4]:
square_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
square_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
diagonal_matrix = np.diag([1, 2, 3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [6]:
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
symmetric_matrix = np.array([[1,2,3], [2, 4, 5], [3, 5, 6]])
symmetric_matrix

array([[1, 2, 3],
       [2, 4, 5],
       [3, 5, 6]])

Q2.	The shares of three companies A, B, and C are 1 million won, 800,000 won, and 500,000 won, respectively. We want to find the amount required to purchase 3, 4, and 5 shares of these stocks, respectively.

1)	Express the stocks’ price and quantity as p vector and n vector, respectively and coded with NumPy.

In [8]:
p = np.array([1000000, 800000, 500000])
n = np.array([3, 4, 5])
p, n

(array([1000000,  800000,  500000]), array([3, 4, 5]))

2)	The amount required to purchase stocks is expressed by multiplication, and the value is calculated by Numpy operation. 

In [9]:
amount_required = np.dot(p, n)
amount_required

8700000

Q3.	When the following code is executed, all data of the MNIST numeric image is converted into vectors to create a single NumPy matrix X. Use this matrix to solve the following problem.

In [10]:
from sklearn.datasets import load_digits
X=load_digits().data

1)	Find the similarity between the first image and the tenth image using dot product.

In [11]:
np.dot(X[0], X[9])

2807.0

2)	Find the similarity for a combination of all images using the dot product, how would it be efficient to implement it (hint: using matrices and multiplication of matrices)

In [12]:
similarity_matrix = np.dot(X, X.T)
similarity_matrix

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

Q4. The Boston house price problem is a problem of predicting the housing price of each town in Boston, USA using features such as the crime rate and air pollution in the area. It can be imported from the scikit-learn package. Find the weight vector x when the Boston house price problem is solved with the linear prediction model Ax= ̂b Matrix and vector data can be obtained as follows. Here, to simplify the problem, we limited the input data to crime rate (CRIM), air quality (NOX), number of rooms (RM), and age (AGE), and only four data were used.
Run the code below to check whether the magnitude or sign of the weight vector obtained from running the program is consistent the common notion. In order to find it, interpret the printed output for all the factors: CRIM, NOX, RM and AGE.  
(※ Write the interpreted output like the house price is in inverse proportion to the crime rate (CRIM).)


In [13]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target
A=X[:4, [0,4,5,6]] # ‘CRIM’,’NOX’,’RM’,’AGE’
b=y[:4]


C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset 

In [14]:
x = np.linalg.solve(A, b)
print('Weight vector (x):', x)

Weight vector (x): [-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


Q5.	Find the weight vector w when the Boston house price problem is solved with the linear prediction model X_w = y ̂ by the least-squares method. Matrix and vector data can be obtained as follows. 
(※ This is the question related to question 4.)


In [15]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target


1)	Run the program above to check whether the magnitude or sign of the weight vector obtained from running the program is consistent the common notion. In order to find it, interpret the printed output for all the factors suggested above.  
(※ Write the interpreted output like “the house price is in inverse proportion to the crime rate (CRIM)”.)


In [16]:

w = np.linalg.lstsq(X, y, rcond=None)[0]
feature_names = boston.feature_names
for i, feature in enumerate(feature_names):
    print(f"{feature}: {w[i]}")

CRIM: -0.09289651702764082
ZN: 0.04871495518300208
INDUS: -0.0040599795750677
CHAS: 2.85399881999393
NOX: -2.8684363704128013
RM: 5.9281477790526935
AGE: -0.007269334576053091
DIS: -0.9685141573950702
RAD: 0.17115112829437976
TAX: -0.009396215397158958
PTRATIO: -0.3921909262948517
B: 0.014905610228201836
LSTAT: -0.41630447073745525


2)	Explain how the result differs from the value obtained in Question 4.

In conclusion, the weight vectors obtained from the linear prediction models differ in their values, number of elements, and interpretations of the weights. This is due to the fact that Question 4 used a subset of features, while Question 5 considered all features in the Boston housing dataset.

Q6.	The ratings given by three users a, b, and c to 4 movies are expressed as vectors as follows.

In [17]:
a=np.array([[4],[5],[2],[2]])
b=np.array([[4],[0],[2],[0]])
c=np.array([[2],[2],[0],[1]])

1) The distance between b and c is the shortest in Euclidean space, and the distance between a and be is the longest. 


In [18]:
distance_b_c = np.linalg.norm(b - c)
distance_a_b = np.linalg.norm(a - b)
distance_a_c = np.linalg.norm(a - c)

print("Euclidean distance between b and c:", distance_b_c)
print("Euclidean distance between a and b:", distance_a_b)
print("Euclidean distance between a and c:", distance_a_c)

Euclidean distance between b and c: 3.605551275463989
Euclidean distance between a and b: 5.385164807134504
Euclidean distance between a and c: 4.242640687119285


So, The distance between b and c is the shortest in Euclidean space, and the distance between a and be is the longest. 

2) The distance between a and be is the shortest in Cosine distance, and the distance between b and c is the longest.  

In [19]:
cosine_distance_a_b = np.linalg.norm(a - b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosine_distance_b_c = np.linalg.norm(b - c) / (np.linalg.norm(b) * np.linalg.norm(c))
cosine_distance_a_c = np.linalg.norm(a - c) / (np.linalg.norm(a) * np.linalg.norm(c))


print("Cosine distance between a and b:", cosine_distance_a_b)
print("Cosine distance between b and c:", cosine_distance_b_c)
print("Cosine distance between a and c:", cosine_distance_a_c)

Cosine distance between a and b: 0.17202277969703278
Cosine distance between b and c: 0.26874192494328497
Cosine distance between a and c: 0.20203050891044214


Q7.	Find the derivative that differentiates the following function using SymPy. In this expression, k, a, and b are constants, not variables.

In [20]:
import sympy as sp

	f(x) = x^3-1

In [21]:
x = sp.Symbol('x')
f1 = x**3-1
sp.diff(f1, x)

3*x**2

	f(x) = log⁡(x^2-3k)

In [22]:
x, k = sp.symbols('x k')
f2 = sp.log(x**2-3*k)
sp.diff(f2, x)

2*x/(-3*k + x**2)

	f(x) =exp(〖ax〗^b)

In [23]:
x, a, b = sp.symbols('x a b')
f3 = sp.exp((a*x)**b)
sp.diff(f3, x)

b*(a*x)**b*exp((a*x)**b)/x

Q8. Find the first and second partial derivatives f_x,f_y,f_xx,f_xy,f_yx,f_yy for the following function using SymPy.

In [24]:
f_x = sp.diff(f1, x)
f_x

3*x**2

In [25]:
f_xx = sp.diff(f_x, x)
f_xx

6*x